# Workflow to validate that the docker image serving our app works as 
# expected BEFORE we push it to GCP. No need to push it to GCP and then 
# find out it doesn't work.

# NOTE: The linux/amd64 image is only built once in this workflow. 
# The image is built once, and the following steps use the internal 
# cache from the first Build and push step. The second Build and push 
# step only builds linux/arm64. (we want to test arm for macs :) )

name: Validate Docker Image of Streamlit App 

on:
  push:
    branches:
      - "github-actions"

env:
  TEST_TAG: raixsplitter/brainzapp:test
  LATEST_TAG: raixsplitter/brainzapp:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}